vault_file: "vault.txt"
embeddings_file: "vault_embeddings.json"
top_k: 7
system_message: "You are a helpful assistanat that is expert in extracting the most useful information fro the given text"

openai:
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 1000
    api_key: "" # in the environment variables
